define local_as = 64512;
define public_ipv4 = 87.249.129.102;
define public_ipv6 = 2a02:6ea0:c75f:1::1;
define neighbor_as = 40806;
define neighbor_ipv4 = 87.249.129.100;
define neighbor_ipv6 = 2a02:6ea0:c75f::1;

define node = "fra.ns2";
define pop = "fra";
define cn = "eu";

function no_advertise(int asn) {
    # Peering.cz
    if asn < 65536 then {
        bgp_community.add((0, asn));
    } else {
        bgp_ext_community.add((ro, 0, asn));
    }
}

function local_filter() {
    # CDN77: do not advertise to backbone
    bgp_community.add((60068, 60010));
    # CDN77: do not advertise to Orange
    bgp_community.add((60068, 40260));

    # Peering.cz: advertise to Frankfurt
    bgp_community.add((61195, 3004));

    no_advertise(3216); # VimpelCom
    no_advertise(4766); # Korea Telecom
    no_advertise(8359); # MTS
    no_advertise(9498); # Bharti
    no_advertise(24482); # SG.GS
    no_advertise(34927); # iFog
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(137409); # GSL
    no_advertise(139901); # Startrek Telecom
}
