define pool = "ns2";

template bgp pool_bgp {}

protocol static grapheneos_ipv4_route {
    ipv4;
    route 23.149.125.0/24 via public_ipv4;
}

protocol static grapheneos_ipv6_route {
    ipv6;
    route 2602:f4d9:1::/48 via public_ipv6;
    route 2602:f4d9:3::/48 via public_ipv6;
}
