define public_ipv4 = 149.28.240.214;
define public_ipv6 = 2001:19f0:6401:1802:5400:05ff:fef7:7b7e;
define bgp_password = "{{bgp_password}}";

define node = "dal.ns1";
define pop = "dal";
define cn = "na";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((62499, 0, asn)); # DE-CIX Dallas
}

function local_filter() {
    # DE-CIX Dallas: only advertise to peers connected in the same metro region
    bgp_large_community.add((62499, 900, 65212));
}
