define public_ipv4 = 216.238.118.134;
define public_ipv6 = 2001:19f0:b800:14a9:5400:05ff:feca:f136;
define bgp_password = "{{bgp_password}}";

define node = "sao.ns1";
define pop = "sao";
define cn = "sa";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((65000, 0, asn)); # IX.br
}

function local_filter() {
    # IX.br: do not advertise to peers with RTT > 100ms
    bgp_large_community.add((65010, 0, 100));
}
