define pool = "staging";
define cdn77 = false;
define misaka = false;

template bgp pool_bgp {
    authentication md5;
    password bgp_password;
}

protocol static grapheneos_ipv4_route {
    ipv4;
}

protocol static grapheneos_ipv6_route {
    ipv6;
    route 2602:f4d9:4::/48 via public_ipv6;
}
