define local_as = 64512;
define public_ipv4 = 91.246.30.3;
define public_ipv6 = 2602:f4d9:5:2::1;
define neighbor_as = 40806;
define neighbor_ipv4 = 91.246.30.1;
define neighbor_ipv6 = 2602:f4d9:5::1;

define node = "yto.ns2";
define pop = "yto";
define cn = "na";
define cdn77 = false;

function no_advertise(int asn) {
    bgp_large_community.add((57369, 0, asn)); # ONIX

    # TorIX
    if asn < 65536 then {
        bgp_community.add((0, asn));
    }
}

function local_filter() {
    # Xenyth: prepend 1x to Arelion
    bgp_community.add((835, 20041));

    # Xenyth: prepend 1x to GTT
    bgp_community.add((835, 20051));

    # Xenyth: prepend 1x to Zayo
    bgp_community.add((835, 20021));
    # Zayo: set localpref to 60
    bgp_community.add((6461, 5060));

    # Xenyth: do not advertise to HE IPv6 transit
    bgp_community.add((835, 20019));

    # Xenyth: prepend 1x to Microsoft
    bgp_community.add((835, 22021));

    # Xenyth: prepend 1x to TorIX
    bgp_community.add((835, 21001));

    # Xenyth: do not advertise to Google
    bgp_community.add((835, 22009));

    # Xenyth: prepend 1x to Meta
    bgp_community.add((835, 22011));

    if net.type = NET_IP4 then {
        # Xenyth: do not advertise to ONIX
        bgp_community.add((835, 21029));
    } else {
        # Xenyth: prepend 1x to ONIX
        bgp_community.add((835, 21021));
    }

    # Xenyth: prepend 1x to Roblox
    bgp_community.add((835, 22031));
}
