define public_ipv4 = 192.248.159.52;
define public_ipv6 = 2001:19f0:7400:8669:5400:05ff:fec3:f3f8;
define bgp_password = "{{bgp_password}}";

define node = "lon.ns1";
define pop = "lon";
define cn = "eu";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((8714, 0, asn)); # LINX
}

function local_filter() {}
