define public_ipv4 = 192.248.159.52;
define public_ipv6 = 2001:19f0:7400:8669:5400:05ff:fec3:f3f8;
define bgp_password = "{{bgp_password}}";

define node = "lon.ns1";
define pop = "lon";
define cn = "eu";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((8714, 0, asn)); # LINX
}

function local_filter() {
    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(6667); # Elisa
    no_advertise(8359); # MTS
    no_advertise(8473); # Bahnhof
    no_advertise(8764); # Telia Lietuva
    no_advertise(9498); # Bharti
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(24482); # SG.GS
    no_advertise(37738); # HOSTOWEB
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(137367); # iForte Solusi Infotek
    no_advertise(139901); # Startrek Telecom
}
