define local_as = 40806;
define neighbor_as = 64515;
define neighbor_ipv4 = 169.254.169.254;
define neighbor_ipv6 = 2001:19f0:ffff::1;

define pool = "ns1";
define cdn77 = false;
define misaka = false;

template bgp pool_bgp {
    authentication md5;
    password bgp_password;
}

protocol static grapheneos_ipv4_route {
    ipv4;
    route 23.149.124.0/24 via public_ipv4;
}

protocol static grapheneos_ipv6_route {
    ipv6;
    route 2602:f4d9::/48 via public_ipv6;
    route 2602:f4d9:2::/48 via public_ipv6;
}
