define public_ipv4 = 66.135.8.22;
define public_ipv6 = 2001:19f0:1000:c0d4:5400:05ff:fec1:7c21;
define bgp_password = "{{bgp_password}}";

define node = "ewr.ns1";
define pop = "ewr";
define cn = "na";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((13538, 0, asn)); # NYIIX
    bgp_large_community.add((63034, 0, asn)); # DE-CIX New York
}

function local_filter() {
    # DE-CIX New York: only advertise to peers connected in the same metro region
    bgp_large_community.add((63034, 900, 65212));
}
