define public_ipv4 = 66.42.74.68;
define public_ipv6 = 2001:19f0:8001:0438:5400:05ff:fec1:9dbd;
define bgp_password = "{{bgp_password}}";

define node = "sea.ns1";
define pop = "sea";
define cn = "na";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((33108, 0, asn)); # SIX
}

function local_filter() {
    # PCCW: set localpref to 60 beyond the connected region
    bgp_community.add((3491, 51912));
    # PCCW: prepend 2x to all peers in Europe
    bgp_community.add((3491, 50302));
    # PCCW: prepend 2x to all peers in Asia
    bgp_community.add((3491, 50402));
    # PCCW: prepend 2x to all peers in Africa
    bgp_community.add((3491, 50502));
    # PCCW: prepend 2x to all peers in Australia
    bgp_community.add((3491, 50702));

    # Comcast: set localpref to 100 (below peers and transit)
    bgp_community.add((7922, 100));
    # Comcast: do not advertise to China Unicom
    bgp_community.add((65100, 4837));
    # Comcast: do not advertise to Orange
    bgp_community.add((65100, 5511));
    # Comcast: do not advertise to TATA
    bgp_community.add((65100, 6453));

    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(6667); # Elisa
    no_advertise(8359); # MTS
    no_advertise(8473); # Bahnhof
    no_advertise(8764); # Telia Lietuva
    no_advertise(9498); # Bharti
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(24482); # SG.GS
    no_advertise(37738); # HOSTOWEB
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(137367); # iForte Solusi Infotek
    no_advertise(139901); # Startrek Telecom
    no_advertise(215638); # Cilix
}
