define local_as = 40806;
define public_ipv4 = 38.175.105.122;
define public_ipv6 = 2a0e:6901:410:ab:26a3:f0ff:fe4a:c8d6;
define neighbor_as = 57695;
define neighbor_ipv4 = 100.100.0.0;
define neighbor_ipv6 = 2a0b:4342:ffff::;

define node = "sjc.ns2";
define pop = "sjc";
define cn = "na";

function no_advertise(int asn) {
    bgp_ext_community.add((rt, 65009, asn)); # Misaka.io
    bgp_large_community.add((24115, 0, asn)); # Equinix
}

function local_filter() {
    # Misaka.io: do not advertise to Google
    bgp_ext_community.add((rt, 65009, 15169));

    # Misaka.io: do not advertise to OVHcloud
    bgp_ext_community.add((rt, 65009, 16276));

    # Misaka.io: prepend 1x to Equinix
    bgp_ext_community.add((rt, 65001, 24115));
    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    # Misaka.io: prepend 1x to i3D.net
    bgp_ext_community.add((rt, 65001, 49544));

    # CDN77: do not advertise to backbone
    bgp_community.add((60068, 60010));
    # CDN77: do not advertise to Orange
    bgp_community.add((60068, 40260));
}
