define local_as = 40806;
define public_ipv4 = 194.156.163.89;
define public_ipv6 = 2407:b9c0:e002:226:26a3:f0ff:fe47:8f06;
define neighbor_as = 57695;
define neighbor_ipv4 = 100.100.0.0;
define neighbor_ipv6 = 2a0b:4342:ffff::;

define node = "sin.ns2";
define pop = "sin";
define cn = "as";
define cdn77 = true;
define misaka = true;

function no_advertise(int asn) {
    bgp_ext_community.add((rt, 65009, asn)); # Misaka.io
    bgp_large_community.add((24115, 0, asn)); # Equinix
    bgp_large_community.add((38137, 0, asn)); # DE-CIX ASEAN
    bgp_large_community.add((50952, 0, asn)); # GNM-IX
    bgp_large_community.add((55518, 0, asn)); # SGIX
}

function local_filter() {
    # Misaka.io: prepend 1x to Equinix
    bgp_ext_community.add((rt, 65001, 24115));
    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    # Misaka.io: prepend 1x to SGIX
    bgp_ext_community.add((rt, 65001, 55518));
    # Misaka.io: enable SGIX
    bgp_community.add((917, 49796));

    # CDN77: do not advertise to BBIX Singapore due to lack of BGP community support
    bgp_community.add((60068, 50390));

    # Misaka.io: do not advertise to GSL
    bgp_ext_community.add((rt, 65009, 137409));

    # DE-CIX ASEAN: do not advertise to all
    bgp_large_community.add((38137, 0, 0));
    # DE-CIX ASEAN: advertise to South East Asia
    bgp_large_community.add((38137, 913, 35));
    # DE-CIX ASEAN: advertise to Brunei
    bgp_large_community.add((38137, 913, 96));
    # DE-CIX ASEAN: advertise to Indonesia
    bgp_large_community.add((38137, 913, 360));
    # DE-CIX ASEAN: advertise to Malaysia
    bgp_large_community.add((38137, 913, 458));
    # DE-CIX ASEAN: advertise to Singapore
    bgp_large_community.add((38137, 913, 702));
}
