define public_ipv4 = 208.85.20.188;
define public_ipv6 = 2a05:f480:2800:24b7:5400:06ff:fe01:ce01;
define bgp_password = "{{bgp_password}}";

define node = "mad.ns1";
define pop = "mad";
define cn = "eu";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((6895, 0, asn)); # ESpanix Madrid Lower LAN
    bgp_large_community.add((48793, 0, asn)); # DE-CIX Madrid
}

function local_filter() {
    # DE-CIX Madrid: only advertise to peers connected in the same metro region
    bgp_large_community.add((48793, 900, 65212));
}
