define public_ipv4 = 45.76.227.130;
define public_ipv6 = 2001:19f0:5c00:446d:5400:06ff:fe0b:0e77;
define bgp_password = "{{bgp_password}}";

define node = "chi.ns1";
define pop = "chi";
define cn = "na";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((24115, 0, asn)); # Equinix
    bgp_large_community.add((62760, 0, asn)); # DE-CIX Chicago
}

function local_filter() {
    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    # DE-CIX Chicago: only advertise to peers connected in the same metro region
    bgp_large_community.add((62760, 900, 65212));
}
