define public_ipv4 = 139.180.154.140;
define public_ipv6 = 2401:c080:1400:4890:5400:05ff:fec2:23b0;
define bgp_password = "{{bgp_password}}";

define node = "sin.ns1";
define pop = "sin";
define cn = "as";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((24115, 0, asn)); # Equinix
    bgp_large_community.add((55518, 0, asn)); # SGIX
}

function local_filter() {
    # PCCW: set localpref to 60 beyond the connected region
    bgp_community.add((3491, 51912));
    # PCCW: prepend 2x to all peers in North America
    bgp_community.add((3491, 50102));
    # PCCW: prepend 2x to all peers in Europe
    bgp_community.add((3491, 50302));
    # PCCW: prepend 2x to all peers in Africa
    bgp_community.add((3491, 50502));
    # PCCW: prepend 2x to all peers in Australia
    bgp_community.add((3491, 50702));

    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(6667); # Elisa
    no_advertise(8359); # MTS
    no_advertise(8473); # Bahnhof
    no_advertise(8764); # Telia Lietuva
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(37738); # HOSTOWEB
    no_advertise(215638); # Cilix
}
