define local_as = 40806;
define public_ipv4 = 198.98.56.238;
define public_ipv6 = 2605:6400:0010:0c41:de92:c534:326a:711a;
define neighbor_as = 53667;
define neighbor_ipv4 = 169.254.169.179;
define neighbor_ipv6 = 2605:6400:ffff::2;
define bgp_password = "{{bgp_password}}";

define pop = "nyc";

function no_advertise(int asn) {}

function local_filter() {}
