define public_ipv4 = 80.240.20.200;
define public_ipv6 = 2a05:f480:1800:2acd:5400:05ff:fec2:23a1;
define bgp_password = "{{bgp_password}}";

define node = "fra.ns1";
define pop = "fra";
define cn = "eu";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((6695, 0, asn)); # DE-CIX Frankfurt
}

function local_filter() {
    # DE-CIX Frankfurt: only advertise to peers connected in the same metro region
    bgp_large_community.add((6695, 900, 65212));

    # Vultr: do not advertise to DE-CIX Hamburg
    bgp_large_community.add((20473, 6000, 43252));

    # Vultr: do not advertise to DE-CIX Munich
    bgp_large_community.add((20473, 6000, 47228));

    # Vultr: do not advertise to DE-CIX Dusseldorf
    bgp_large_community.add((20473, 6000, 56890));

    no_advertise(3216); # VimpelCom
    no_advertise(4766); # Korea Telecom
    no_advertise(6667); # Elisa
    no_advertise(8359); # MTS
    no_advertise(8473); # Bahnhof
    no_advertise(8764); # Telia Lietuva
    no_advertise(9498); # Bharti
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(24482); # SG.GS
    no_advertise(37738); # HOSTOWEB
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(137367); # iForte Solusi Infotek
    no_advertise(139901); # Startrek Telecom
    no_advertise(215638); # Cilix
}
