define public_ipv4 = 139.180.154.140;
define public_ipv6 = 2401:c080:1400:4890:5400:05ff:fec2:23b0;
define bgp_password = "{{bgp_password}}";

define node = "sin.ns1";
define pop = "sin";
define cn = "as";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((24115, 0, asn)); # Equinix
    bgp_large_community.add((55518, 0, asn)); # SGIX
}

function local_filter() {
    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));
}
