define public_ipv4 = 65.20.91.33;
define public_ipv6 = 2401:c080:2400:1814:5400:05ff:fec5:d503;
define bgp_password = "{{bgp_password}}";

define node = "bom.ns1";
define pop = "bom";
define cn = "as";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((24193, 0, asn)); # AMS-IX Mumbai
    bgp_large_community.add((49378, 0, asn)); # Extreme IX Mumbai
    bgp_large_community.add((59200, 0, asn)); # DE-CIX Mumbai
}

function local_filter() {
    # Vultr: do not advertise to Telstra Global
    bgp_large_community.add((20473, 6000, 4637));

    # Vultr: do not advertise to TATA Communications
    bgp_large_community.add((20473, 6000, 4755));

    # Bharti: don't export to international peers
    bgp_community.add((9498, 55));

    # DE-CIX Mumbai: only advertise to peers connected in the same metro region
    bgp_large_community.add((59200, 900, 65212));

    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(6667); # Elisa
    no_advertise(8359); # MTS
    no_advertise(8473); # Bahnhof
    no_advertise(8764); # Telia Lietuva
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(37738); # HOSTOWEB
    no_advertise(137367); # iForte Solusi Infotek
    no_advertise(215638); # Cilix
}
