define local_as = 40806;
define public_ipv4 = 103.170.233.149;
define public_ipv6 = 2407:b9c0:1:2af:26a3:f0ff:fe46:bede;
define neighbor_as = 57695;
define neighbor_ipv4 = 100.100.0.0;
define neighbor_ipv6 = 2a0b:4342:ffff::;

define node = "tyo.ns2";
define pop = "tyo";
define cn = "as";

function no_advertise(int asn) {
    bgp_ext_community.add((rt, 65009, asn)); # Misaka.io
    bgp_large_community.add((24115, 0, asn)); # Equinix

    # BBIX and JPNAP
    if asn < 65536 then {
        bgp_community.add((0, asn));
    }
}

function local_filter() {
    # Misaka.io: do not advertise to Google
    bgp_ext_community.add((rt, 65009, 15169));

    # Misaka.io: do not advertise to OVHcloud
    bgp_ext_community.add((rt, 65009, 16276));

    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    # Misaka.io: prepend 1x to i3D.net
    bgp_ext_community.add((rt, 65001, 49544));

    # CDN77: do not advertise to backbone
    bgp_community.add((60068, 60010));
    # CDN77: do not advertise to Orange
    bgp_community.add((60068, 40260));

    # Misaka.io: do not advertise to GSL
    bgp_ext_community.add((rt, 65009, 137409));

    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(8359); # MTS
    no_advertise(9498); # Bharti
    no_advertise(58715); # Earth Telecommunication
    no_advertise(139901); # Startrek Telecom
}
