define public_ipv4 = 66.42.42.15;
define public_ipv6 = 2001:19f0:7001:5695:5400:05ff:fec4:e394;
define bgp_password = "{{bgp_password}}";

define node = "tyo.ns1";
define pop = "tyo";
define cn = "as";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((23815, 0, asn)); # JPIX
    bgp_large_community.add((24115, 0, asn)); # Equinix

    # BBIX and JPNAP
    if asn < 65536 then {
        bgp_community.add((0, asn));
    }
}

function local_filter() {
    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));
}
