define local_as = 64512;
define public_ipv4 = 121.127.40.57;
define public_ipv6 = 2a02:6ea0:d207::1;
define neighbor_as = 40806;
define neighbor_ipv4 = 121.127.40.19;
define neighbor_ipv6 = 2a02:6ea0:d206::1;

define node = "dal.ns2";
define pop = "dal";
define cn = "na";
define cdn77 = true;
define misaka = false;

function no_advertise(int asn) {}

function local_filter() {}
