define public_ipv4 = 45.76.227.130;
define public_ipv6 = 2001:19f0:5c00:446d:5400:06ff:fe0b:0e77;
define bgp_password = "{{bgp_password}}";

define node = "chi.ns1";
define pop = "chi";
define cn = "na";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((24115, 0, asn)); # Equinix
    bgp_large_community.add((62760, 0, asn)); # DE-CIX Chicago
}

function local_filter() {
    # PCCW: set localpref to 60 beyond the connected region
    bgp_community.add((3491, 51912));
    # PCCW: prepend 2x to all peers in Europe
    bgp_community.add((3491, 50302));
    # PCCW: prepend 2x to all peers in Asia
    bgp_community.add((3491, 50402));
    # PCCW: prepend 2x to all peers in Africa
    bgp_community.add((3491, 50502));
    # PCCW: prepend 2x to all peers in Australia
    bgp_community.add((3491, 50702));

    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    # DE-CIX Chicago: only advertise to peers connected in the same metro region
    bgp_large_community.add((62760, 900, 65212));

    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(6667); # Elisa
    no_advertise(8359); # MTS
    no_advertise(8473); # Bahnhof
    no_advertise(8764); # Telia Lietuva
    no_advertise(9498); # Bharti
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(24482); # SG.GS
    no_advertise(37738); # HOSTOWEB
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(137367); # iForte Solusi Infotek
    no_advertise(139901); # Startrek Telecom
    no_advertise(215638); # Cilix
}
