define public_ipv4 = 70.34.206.66;
define public_ipv6 = 2a05:f480:2000:2941:5400:06ff:fe0b:d01f;
define bgp_password = "{{bgp_password}}";

define node = "sto.ns1";
define pop = "sto";
define cn = "eu";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((24115, 0, asn)); # Equinix
    bgp_large_community.add((52005, 0, asn)); # Netnod
    bgp_large_community.add((57151, 0, asn)); # STHIX
    bgp_large_community.add((61229, 0, asn)); # SONIX
}

function local_filter() {
    # Equinix: advertise to all peers
    bgp_large_community.add((24115, 1, 24115));
    # Equinix: do not advertise to peers with RTT > 200ms
    bgp_large_community.add((24115, 2, 200));

    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(8764); # Telia Lietuva
    no_advertise(9498); # Bharti
    no_advertise(13000); # Leon
    no_advertise(13110); # INEA
    no_advertise(20804); # EXATEL
    no_advertise(24482); # SG.GS
    no_advertise(37738); # HOSTOWEB
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(137367); # iForte Solusi Infotek
    no_advertise(139901); # Startrek Telecom
    no_advertise(215638); # Cilix
}
