define local_as = 40806;
define public_ipv4 = 38.175.100.57;
define public_ipv6 = 2a0e:6902:5010:d9:26a3:f0ff:fe48:de47;
define neighbor_as = 57695;
define neighbor_ipv4 = 100.100.0.0;
define neighbor_ipv6 = 2a0b:4342:ffff::;

define node = "mia.ns2";
define pop = "mia";
define cn = "na";
define cdn77 = true;
define misaka = true;

function no_advertise(int asn) {
    bgp_ext_community.add((rt, 65009, asn)); # Misaka.io
    bgp_large_community.add((63221, 0, asn)); # FL-IX
}

function local_filter() {
    # CDN77: do not advertise to FL-IX
    bgp_community.add((60068, 50690));

    # Misaka.io: prepend 1x to FL-IX
    bgp_ext_community.add((rt, 65001, 63221));
}
