define local_as = 64512;
define public_ipv4 = 91.246.30.3;
define public_ipv6 = 2602:f4d9:5:2::1;
define neighbor_as = 40806;
define neighbor_ipv4 = 91.246.30.1;
define neighbor_ipv6 = 2602:f4d9:5::1;

function no_advertise(int asn) {
    bgp_large_community.add((57369, 0, asn)); # ONIX

    # TorIX
    if asn < 65536 then {
        bgp_community.add((0, asn));
    }
}

filter grapheneos_filter {
    # Xenyth: prepend 1x to Arelion
    bgp_community.add((835, 20041));
    # Arelion: set localpref to 50 beyond the connected region
    bgp_community.add((1299, 10050));
    # Arelion: prepend 2x to all peers in Europe
    bgp_community.add((1299, 2002));
    # Arelion: prepend 2x to all peers in Asia & Pacific
    bgp_community.add((1299, 7002));
    # Arelion: prepend 2x to China Unicom in Europe and North America
    bgp_community.add((1299, 2872));
    bgp_community.add((1299, 5872));
    # Arelion: prepend 2x to China Telecom in Europe and North America
    bgp_community.add((1299, 2882));
    bgp_community.add((1299, 5882));

    # Xenyth: prepend 1x to GTT
    bgp_community.add((835, 20051));
    # GTT: set localpref way below peers in configured regions
    bgp_community.add((3257, 1960));
    # GTT: set localpref in Europe
    bgp_community.add((3257, 2010));
    # GTT: set localpref in Asia
    bgp_community.add((3257, 2011));
    # GTT: set localpref in Africa
    bgp_community.add((3257, 2012));
    # GTT: set localpref in South America
    bgp_community.add((3257, 2013));
    # GTT: prepend 2x in Europe
    bgp_community.add((3257, 2492));
    # GTT: prepend 2x in Asia
    bgp_community.add((3257, 2592));
    # GTT: prepend 2x in Africa
    bgp_community.add((3257, 2692));
    # GTT: prepend 2x in South America
    bgp_community.add((3257, 2892));

    # Xenyth: prepend 1x to Zayo
    bgp_community.add((835, 20021));
    # Zayo: set localpref to 60
    bgp_community.add((6461, 5060));

    # Xenyth: do not advertise to HE IPv6 transit
    bgp_community.add((835, 20019));

    # Xenyth: prepend 1x to TORIX
    bgp_community.add((835, 21001));

    # Xenyth: do not advertise to Google
    bgp_community.add((835, 22009));

    # Xenyth: prepend 1x to ONIX
    bgp_community.add((835, 21021));

    no_advertise(3204); # xTom V.PS
    no_advertise(3214); # xTom
    no_advertise(3216); # VimpelCom
    no_advertise(3303); # Swisscom
    no_advertise(4766); # Korea Telecom
    no_advertise(8359); # MTS
    no_advertise(9002); # RETN
    no_advertise(9498); # Bharti
    no_advertise(19151); # 365 Data Centers
    no_advertise(24013); # xTom DNS.SB
    no_advertise(24482); # SG.GS
    no_advertise(26042); # FiberState
    no_advertise(26141); # CUBEPATH
    no_advertise(32098); # Flō Networks (Transtelco)
    no_advertise(57463); # NetIX
    no_advertise(57974); # Teracast
    no_advertise(58453); # China Mobile International
    no_advertise(58715); # Earth Telecommunication
    no_advertise(139901); # Startrek Telecom

    accept;
}
