define public_ipv4 = 140.82.23.46;
define public_ipv6 = 2001:19f0:6000:2dcd:5400:05ff:fec1:97db;
define bgp_password = "{{bgp_password}}";

define node = "lax.ns1";
define pop = "lax";
define cn = "na";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr

    # Any2West
    if asn < 65536 then {
        bgp_community.add((0, asn));
    } else {
        bgp_ext_community.add((ro, 0, asn));
    }
}

function local_filter() {}
