define public_ipv4 = 45.63.28.82;
define public_ipv6 = 2401:c080:1800:141d:5400:05ff:fec5:d41b;
define bgp_password = "{{bgp_password}}";

define node = "syd.ns1";
define pop = "syd";
define cn = "oc";

function no_advertise(int asn) {
    bgp_large_community.add((20473, 6000, asn)); # Vultr
    bgp_large_community.add((7606, 0, asn)); # NSW-IX
    bgp_large_community.add((24224, 0, asn)); # EdgeIX
    bgp_large_community.add((58941, 65000, asn)); # MegaIX Sydney, Perth & Adelaide
}

function local_filter() {
    # Telstra: do not advertise outside Australia and New Zealand via Telstra Global
    bgp_community.add((1221, 1110));

    # AAPT: do not advertise to transit, only customers and peers
    bgp_community.add((2764, 6));
}
