#!/bin/bash

set -o errexit -o nounset -o pipefail

status=0
if [[ $HOSTNAME == 0-ns1 ]]; then
    replicas=({1..3}.ns1.grapheneos.org)
elif [[ $HOSTNAME == 0-ns2 ]]; then
    replicas=({1..2}.ns2.grapheneos.org)
else
    echo unexpected hostname $HOSTNAME
    exit 1
fi

for replica in ${replicas[@]}; do
    echo
    echo Deploying to $replica
    echo

    rsync -rpcvl --delete --fsync --preallocate /etc/letsencrypt/ $replica:/etc/letsencrypt &&
        ssh root@$replica "nginx -s reload; rsync -rLvc --delete --chmod=D750,F640 --chown root:dnsdist /etc/letsencrypt/live/ /etc/letsencrypt/dnsdist/; dnsdist -c -e 'reloadAllCertificates()'" ||
        status=1
done

exit $status
