#!/bin/bash

set -o errexit -o nounset -o pipefail

servers=(
    ns1.grapheneos.org
    ns2.grapheneos.org
)

declare -A ipv4=(
    [ns1.grapheneos.org]=51.222.14.6
    [ns2.grapheneos.org]=141.94.71.48

)

declare -A ipv6=(
    [ns1.grapheneos.org]=2607:5300:205:200::29e8
    [ns2.grapheneos.org]=2001:41d0:304:200::528
)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    cp pdns.conf pdns.conf.tmp
    sed -i "s/{ipv4}/${ipv4[$server]}/g; s/{ipv6}/${ipv6[$server]}/g" pdns.conf.tmp
    rsync -pcv --chmod=F644 pdns.conf.tmp $remote:/etc/powerdns/pdns.conf
    rsync -pcv --chmod=F644 zones.yaml $remote:/etc/powerdns/zones.yaml
    # need to restart rather than reloading for arbitrary configuration changes
    ssh $remote systemctl restart pdns
    # space out restarts so clients don't get multiple failures
    sleep 5

    echo
done
