#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch nginx-lock
exec {fd}< nginx-lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

. servers.sh

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    rm -rf nginx-tmp
    cp -a nginx nginx-tmp
    sed -i s/{{subdomain}}/ns1.staging/g nginx-tmp/nginx.conf
    gixy nginx-tmp/nginx.conf
    rsync -rpcv --chmod=D755,F644 --delete --fsync --preallocate nginx-tmp/{nginx.conf,mime.types} $remote:/etc/nginx/
    ssh $remote systemctl reload nginx

    echo
done
