#!/bin/bash

set -o errexit -o nounset -o pipefail

touch dnsdist-lock
exec {fd}< dnsdist-lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

. servers.sh

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    subdomain=ns1.staging

    cp dnsdist.conf dnsdist.conf.tmp
    sed -i "s/{{subdomain}}/$subdomain/g;s/{{threads}}/${threads[$server]:-1}/g" dnsdist.conf.tmp
    rsync -pcv --chmod=F644 --fsync --preallocate dnsdist.conf.tmp $remote:/etc/dnsdist.conf
    rm dnsdist.conf.tmp

    ssh $remote 'usermod -aG tls dnsdist &&
mkdir -pm750 /etc/dnsdist.conf.d &&
chown root:dnsdist /etc/dnsdist.conf.d &&
systemctl enable dnsdist.service &&
systemctl restart dnsdist.service'
done
