#!/bin/bash

set -o errexit -o nounset -o pipefail

dnsdist_conf_tmp=

cleanup() {
    if [[ -n $dnsdist_conf_tmp ]]; then
        rm -f "$dnsdist_conf_tmp"
    fi
}

touch dnsdist-lock
exec {fd}< dnsdist-lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi
trap cleanup EXIT

. servers.sh

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    if [[ $server == *.ns1.grapheneos.org ]]; then
        subdomain=ns1
    else
        subdomain=ns2
    fi

    dnsdist_conf_tmp=$(mktemp dnsdist.conf.tmp.XXXXXXXXXX)
    cp dnsdist.conf "$dnsdist_conf_tmp"
    sed -i "s/{{subdomain}}/$subdomain/g;s/{{threads}}/${threads[$server]:-1}/g" "$dnsdist_conf_tmp"
    rsync -pcv --chmod=F644 --fsync --preallocate "$dnsdist_conf_tmp" $remote:/etc/dnsdist.conf
    rm "$dnsdist_conf_tmp"
    dnsdist_conf_tmp=

    ssh $remote 'usermod -aG tls dnsdist &&
mkdir -pm750 /etc/dnsdist.conf.d &&
chown root:dnsdist /etc/dnsdist.conf.d &&
systemctl enable dnsdist.service &&
systemctl restart dnsdist.service'
done
