#!/bin/bash

set -o errexit -o nounset -o pipefail

pdns_conf_tmp=
zones_tmp=

cleanup() {
    if [[ -n $pdns_conf_tmp ]]; then
        rm -f "$pdns_conf_tmp"
    fi
    if [[ -n $zones_tmp ]]; then
        rm -rf "$zones_tmp"
    fi
}

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi
trap cleanup EXIT

reconfigure=0
if [[ $# -eq 1 ]]; then
    if [[ $1 == reconfigure ]]; then
        reconfigure=1
    else
        echo invalid parameter
        exit 1
    fi
elif [[ $# -ne 0 ]]; then
    echo too many parameters
    exit 1
fi

# use YYYYMMDDSS SOA serial format
old_serial=$(cat serial.txt 2>/dev/null || echo -n $(date -u +"%Y%m%d00"))
serial=$(date -u +"%Y%m%d")
if [[ ${old_serial:0:8} = ${serial} ]]; then
    old_sequence=${old_serial:8:2}
    old_sequence=${old_sequence##0}
    [[ $old_sequence -eq 99 ]] && old_sequence=0
    serial+=$(printf %02d $(( $old_sequence + 1 )))
else
    serial+=00
fi
echo serial: $serial
echo
echo -n $serial > serial.txt

. servers.sh

geoip_subdomain=$(tr -cd a-z0-9 </dev/random | head -c 20 | tee geoip-subdomain.txt) || [[ ${PIPESTATUS[0]} -eq 141 ]]
echo >> geoip-subdomain.txt

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    if [[ $server == *.ns1.grapheneos.org ]]; then
        subdomain=ns1
    else
        subdomain=ns2
    fi

    if (( reconfigure )); then
        pdns_conf_tmp=$(mktemp pdns.conf.tmp.XXXXXXXXXX)
        cp pdns.conf "$pdns_conf_tmp"
        sed -i "s/{{addresses}}/${addresses[$server]}/g;s/{{threads}}/${threads[$server]:-1}/g" "$pdns_conf_tmp"
        rsync -pcv --chmod=644 --fsync --preallocate "$pdns_conf_tmp" $remote:/etc/powerdns/pdns.conf
        rm "$pdns_conf_tmp"
        pdns_conf_tmp=
        ssh $remote 'id -u geoipupdate &>/dev/null || useradd -r geoipupdate -md /var/lib/GeoIP -s /usr/bin/nologin && chown -R geoipupdate:geoipupdate /var/lib/GeoIP && chmod 755 /var/lib/GeoIP'
        rsync -pcv --chmod=755 --fsync --preallocate ipinfo-update pdns-trigger-health-checks $remote:/usr/local/bin/
        rsync -pcv --chown root:geoipupdate --chmod=F640 --fsync --preallocate ipinfo-token.txt $remote:/etc/ipinfo-token.txt
        rsync -prcv --chmod=D755,F644 --fsync --preallocate systemd/system/{ipinfo-update.service,ipinfo-update.timer,pdns.service.d,pdns-trigger-health-checks.{service,timer}} $remote:/etc/systemd/system/
    fi

    rsync -pcv --chmod=644 --fsync --preallocate named.conf $remote:/etc/powerdns/named.conf

    zones_tmp=$(mktemp -d zones.tmp.XXXXXXXXXX)
    cp -r zones/. "$zones_tmp"
    sed -i "s/{{serial}}/$serial/g;s/{{continent}}/${continents[$server]}/g;s/{{country}}/${countries[$server]}/g;s/{{region}}/${regions[$server]}/g;s/{{us_west}}/${us_west[$server]:-false}/g;s/{{ns}}/$subdomain/g;s/{{geoip_subdomain}}/$geoip_subdomain/g" "$zones_tmp"/*.zone
    rsync -prcv --chmod=D755,F644 --delete --fsync --preallocate "$zones_tmp"/ $remote:/etc/powerdns/zones/
    rm -rf "$zones_tmp"
    zones_tmp=

    if (( reconfigure )); then
        ssh $remote 'sleep 5 &&
systemctl daemon-reload &&
systemctl enable --now ipinfo-update.timer pdns.service pdns-trigger-health-checks.timer &&
systemctl restart pdns.service'
    else
        ssh $remote 'pdns_control rediscover && pdns_control reload'
    fi

    echo
done
