#!/bin/bash

set -o errexit -o nounset -o pipefail

. servers.sh

alias rsync='rsync --fsync --preallocate'

deploy_bird() {
    local server=$1
    local remote=root@$1
    local ns=$2

    ssh $remote 'id -u bird &>/dev/null || useradd -r bird -d /'
    rsync -rpcv --chmod=D755,F644 systemd/system/bird.service.d $remote:/etc/systemd/system/
    rsync -pcv --chmod=644 bird.$ns.conf $remote:/etc/bird.conf
    cp bird.$server.conf bird.local.conf
    sed -i "s/{{bgp_password}}/${bgp_password[$server]}/g" bird.local.conf
    rsync -pcv --chmod=644 bird.local.conf $remote:/etc/bird.local.conf
    rm bird.local.conf
}

for server in ${servers[@]}; do
    echo $server

    if [[ $server == *.ns1.grapheneos.org ]]; then
        subdomain=ns1
    elif [[ $server == @(ber.ns2.grapheneos.org|lon.ns2.grapheneos.org|sin.ns2.grapheneos.org) ]]; then
        subdomain=misaka
    else
        subdomain=ns2
    fi

    deploy_bird $server $subdomain

    echo
done
