#!/bin/bash

set -o errexit -o nounset -o pipefail

mkdir -p /var/lib/powerdns
chmod 750 /var/lib/powerdns
chown -R root:powerdns /var/lib/powerdns
rm /var/lib/powerdns/bind-dnssec-db.sqlite3

pdnsutil create-bind-db /var/lib/powerdns/bind-dnssec-db.sqlite3

for key in /etc/powerdns/keys/*.key; do
    pdnsutil import-zone-key $(basename $key | cut -d . -f 1-2) $key
done
