#!/bin/bash

set -o errexit -o nounset -o pipefail

# Calgary currently isn't included since Seattle is our closest location and at
# the time of writing there aren't any relevant remote peers in Calgary which
# would be better off not receiving our routes.

# .switch_id == 3 is Kansas City
# .switch_id == 5 is Calgary
# .switch_id == 10 is Minneapolis

curl -s https://www.seattleix.net/autogen/participants.json | jq -r '
  [
    .member_list[]
    | select(any(.connection_list[].if_list[]?; .switch_id == 3 or .switch_id == 10))
    | .asnum
  ]
  | unique[]
  | "bgp_large_community.add((33108, 0, \(.)));"
'
