#!/bin/bash

set -o errexit -o nounset -o pipefail

servers=(
    0.ns2.grapheneos.org
    1.ns2.grapheneos.org
    2.ns2.grapheneos.org
)

rsync -rcv --fsync --preallocate root@ns1.grapheneos.org:/etc/powerdns/keys/ keys

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    rsync -rcpv --delete --chmod=D750,F640 --chown=root:powerdns --fsync --preallocate keys/ root@$server:/etc/powerdns/keys

    echo
done
